import {createContext,useContext} from 'react'


//IN THE PREVIOUS PROJECT, MINICONTEXT, WE CREATED CONTEXT WITH NO PARAMETERS OR VALUES, BUT NOWWE CAN GIVE DEFAULT VALUES -> WHEN CONTEXT CREATED FOR THE FIRST TIME WHAT VALUES SHOULD BE THERE ALREADY, THERE SHOULD BE DEFAULT OBJECT IN THIS CASE   
//WHENEVER SOMEONE CALLS THIS CONTEXT THEY GET THIS OBJECT TOO, THEY CAN ACCESS THEMEMODE, DARKTHEME FUNCTION ETC
//WE CAN GIVE VARIABLES/METHODS/STATES IN CONTEXT
export const ThemeContext=createContext({
    themeMode:"light",
    darkTheme:()=>{},
    lightTheme:()=>{}
})

//WE MADE SEPARATE FILE FOR PROVIDER AND THEN WRAPPED CHILDREN IN IT IN PREV PROJECT WHEREAS WE CAN DO IT DIRECTLY HERE
export const ThemeProvider=ThemeContext.Provider

//MAKING CUSTOM HOOKS,BY DOING THIS WE DONT NEED TO IMPORT USECONTEXT, AND THEMECONTEXT SEPARATELY, WE JUST NEED TO IMPORT USETHEME AND THAT'S DOING THE JOB
export default function useTheme(){
return useContext(ThemeContext)
}

//THEME PROVIDER SE COMPONENT WRAP KRDENGE, THEMEMODE,DARKTHEME,LIGTTHEME ME SE KCH CHAHYE HOGA TO USETHEME HOOK SE LE LENGE